<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <CodeAnalysisRuleSet>$(ProjectDir)../Cake.Discord.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="$(ProjectDir)../stylecop.json" Link="stylecop.json" />
    <None Include="$(ProjectDir)../.editorconfig" Link=".editorconfig" />
    <None Include="$(ProjectDir)../../README.md" Link="README.md" PackagePath="" Pack="true" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Properties related to packaging -->
    <Authors>Gary Ewan Park</Authors>
    <Copyright>Copyright (c) Cake Contributions 2018 - Present</Copyright>
    <Description>Cake AddIn that extends Cake with ability to send messages to Discord.
This version was build for Cake v$(CakeVersion)</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/cake-contrib/Cake.Discord</PackageProjectUrl>
    <PackageTags>cake;script;build;discord;cake-addin;addin;cake-build</PackageTags>
    <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
    <PackageReleaseNotes>This version was build for Cake v$(CakeVersion).
For details see $(PackageProjectUrl)/releases</PackageReleaseNotes>
    <Version>0.0.0</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cake.Addin.Analyzer" Version="0.1.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Cake.Core" Version="6.0.0" PrivateAssets="All" />
    <PackageReference Include="Cake.Common" Version="6.0.0" PrivateAssets="All" />
    <PackageReference Include="CakeContrib.Guidelines" Version="1.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="IDisposableAnalyzers" Version="4.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>
